Preserve EXTNAME value for compressed files.
opencadc/nom-tam-fits pull request #17
Opened 2022-08-17 19:56 UTC by at88mph

2022-09-07 18:45 UTC, pdowler requested changes

2022-09-07 18:45 UTC, pdowler commented on .github/workflows/java-build.yml
> +#      run: ./gradlew --info clean build javadoc
If maven is better for running all the existing tests that;s fine, but can we keep the gradle build as well (can be separate step at the end? If it doesn't work, then I can't publish the jars to central...

2022-09-07 21:18 UTC, pdowler commented on .github/workflows/java-build.yml
> +#      run: ./gradlew --info clean build javadoc
it can be `gradle clean assemble javadoc` since unit tests are run via maven

2022-09-08 17:43 UTC, at88mph commented on .github/workflows/java-build.yml
> +#      run: ./gradlew --info clean build javadoc
Done.

2022-09-12 17:18 UTC, pdowler approved these changes

2022-09-12 17:18 UTC, merged