Tile stream
opencadc/nom-tam-fits pull request #2
Opened 2020-12-17 15:10 UTC by at88mph

Sorry, it's a big one.

The `StreamingImageData` class will write out properly, and delegate reading into it to the Tiler.  The Tiler had to be modified to allow proper streaming from the `RandomAccess` Object.

The way the `StreamingImageData` is used can be a little cumbersome given the amount of state the `Fits` Object, and its HDUs, hold.  I've had to clone and make copies where necessary to remove references.

With these changes, one can set the `streamWriteFlag` in the `Fits` Object to get a `StreamingImageData` instance in the `ImageHDU`s.  When iterating over HDUs, however, and writing out to another file for tiling, one must still create a new `StreamingImageData` Object but clone the `StandardImageTiler` to preserve the underlying `ReadAccess` object.

2020-12-17 15:11 UTC, at88mph commented
There was effort put into preserving the Maven build, as well.

2021-01-19 21:32 UTC, pdowler commented on src/main/java/nom/tam/image/ImageTiler.java
> +    void getTile(ArrayDataOutput output, int[] corners, int[] lengths) throws FitsException, IOException;
I was not expecting to a need for the above method. Doesn't subsection (corners and lengths) happen during read and therefore everything that is read gets written out?

2021-01-19 21:49 UTC, pdowler commented on src/test/java/nom/tam/util/BufferedFileTest.java
> +    }
Mainly: it seems unclear what these new test methods are trying to test w.r.t the BufferedFile class...

Secondarily: It's worth noting that many FITS data arrays are stored as integers (BITPIX=16 means short, BITPIX=32 means int, could be that BITPIX=64 is used as well but haven't seen it. Testing byte, float, and boolean seems incomplete to me and further reinforces the lack of clarity for the main issue above.

2021-01-19 22:32 UTC, pdowler requested changes

2021-01-19 22:32 UTC, pdowler commented on pom.xml
> +	<version>1.17.0</version>
Would like to see version 1.16.1 here and in build.gradle

2021-01-19 22:41 UTC, pdowler commented on src/main/java/nom/tam/util/MemoryUsage.java
> +
The output below should use the standard logging rather than System.out ... debug level.

2021-01-19 23:26 UTC, at88mph commented on src/test/java/nom/tam/util/BufferedFileTest.java
> +    }
OK.
The `StandardImageTiler` on line 317 makes use of the `MemoryUsage` class.  It just checkpoints every 200 skips along the first dimension of the array.  That tiler will move along the first dimension (using the `incrementPosition` method and then perform a seek in the file.  The `MemoryUsage` class will checkpoint every nth loop to print out, but only after the call to `read(data output, ...)` has been called to show that nothing beyond the cached headers (ones already read) are being put into memory.

2021-01-19 23:29 UTC, at88mph commented on src/main/java/nom/tam/util/MemoryUsage.java
> +
Done.  This library is a mix of Java Logging and System.out.println.

2021-01-20 01:15 UTC, pdowler reviewed
This PR is still a _draft_ and to be honest the amount of "wiring" needed to do this is hard to follow so I can't actually tell if the work is complete or correct... As noted, part of the work still has to be done by the client to make streaming read-to-write work.

2021-01-20 01:19 UTC, pdowler commented on src/test/java/nom/tam/util/BufferedFileTest.java
> +    }
Ah, didn't spot that. thnx. Might be good for the MemoryUsage.checkpoint to check the log level and do nothing if it isn't actually going to output any info. I don't think it's good practice to call `System.gc()` in an app server (esp. frequently and/or in a loop)

2021-01-20 14:20 UTC, at88mph commented on src/test/java/nom/tam/util/BufferedFileTest.java
> +    }
Adding that test is a good suggestion and worked well.  It also exposed that I missed testing with `char`.

2021-01-20 18:25 UTC, pdowler approved these changes

2021-01-20 22:27 UTC, merged